### ISSUE TITLE
Failed to allocate mbuf error for RX when set rss queue to 16

### ISSUE THREAD

**Issue by bjdudu** [vipinpv85/DPDK_SURICATA-4_1_1#10]
When I set the interface rss queue to 16, I got an error, the program worked well when I set rss queue to 8 and 4.

screenshot for the error:
![ips port1 error](https://user-images.githubusercontent.com/3258147/87934548-da687880-cac1-11ea-8950-8c0e9cfe634c.png)

dpdk settings:
![ips dpdk setting](https://user-images.githubusercontent.com/3258147/87934665-100d6180-cac2-11ea-97c2-52fe1e8e3351.png)

**Comment by vipinpv85** [comment]
answer to the problem you are facing is based on the edit you have done `failed to allocate RX queue mbuf`.  Please do the necessary change to `eal-args` to satisfy your queues..
