### ISSUE TITLE
Suricata start failed: No DPDK ports found

### ISSUE THREAD

**Issue by lzskyline** [vipinpv85/DPDK_SURICATA-4_1_1#14]
# suricata --dpdk
19/8/2020 -- 16:01:30 - <Notice> -  DPDK Mode selected
19/8/2020 -- 16:01:30 - <Notice> -  (name:suricatareassembly)
19/8/2020 -- 16:01:30 - <Notice> -  (n:8000)
19/8/2020 -- 16:01:30 - <Notice> - This is Suricata version 4.1.4 (rev 09ee165)
19/8/2020 -- 16:01:30 - <Error> - [ERRCODE: SC_ERR_DPDK_CONFIG(319)] -  No DPDK ports found

There are different from:
https://github.com/vipinpv85/DPDK_SURICATA-4_1_1/issues/5

I can't find  the "mysuricata.cfg" file, I don't even know what format to input into this file.

I found the DPDK options in the "suricate.yml" file, I guess it's a update, but how can I set it?
![image](https://user-images.githubusercontent.com/9845170/90609673-fb45fa00-e236-11ea-98a5-88e91419a4b0.png)

**Comment by lzskyline** [comment]
l2fwd example is worked.
![image](https://user-images.githubusercontent.com/9845170/90612038-15350c00-e23a-11ea-9845-9341ac5867aa.png)

**Comment by vipinpv85** [comment]
humbly suggesting to refer the https://github.com/vipinpv85/DPDK_SURICATA-4_1_1/blob/master/README.md.  There are no `mysuricata.cfg`

**Comment by vipinpv85** [comment]
> l2fwd example is worked.
> ![image](https://user-images.githubusercontent.com/9845170/90612038-15350c00-e23a-11ea-9845-9341ac5867aa.png)

this is more like https://github.com/vipinpv85/DPDK_SURICATA-4_1_1/issues/11. Hence marking this duplicate too.

**Comment by lzskyline** [comment]
Yes, it's similar, could you please tell me how to modify the Makefile or configure.ac ?
just append "-lrte_pmd_e1000 -Wl" to "-lrte_pmd_i40e -Wl", then re-make it?

**Comment by vipinpv85** [comment]
Configure.ac is already having 'lrte_pmd_i40e -Wl'. What are you saying

**Comment by vipinpv85** [comment]
> > l2fwd example is worked.
> > ![image](https://user-images.githubusercontent.com/9845170/90612038-15350c00-e23a-11ea-9845-9341ac5867aa.png)
> 
> this is more like #11. Hence marking this duplicate too.

Your dpdk debugging is incorrect, there is no X710 ports in your system. Recheck your system configuration rather than assuming the cause of errors.

**Comment by lzskyline** [comment]
> > > l2fwd example is worked.
> > > ![image](https://user-images.githubusercontent.com/9845170/90612038-15350c00-e23a-11ea-9845-9341ac5867aa.png)
> > 
> > 
> > this is more like #11. Hence marking this duplicate too.
> 
> Your dpdk debugging is incorrect, there is no X710 ports in your system. Recheck your system configuration rather than assuming the cause of errors.

![image](https://user-images.githubusercontent.com/9845170/90629355-d14e0100-e251-11ea-8428-1aa704b1abd2.png)
![image](https://user-images.githubusercontent.com/9845170/90629465-02c6cc80-e252-11ea-8c09-05dd94e805b3.png)
But I run the exmaple "l2fwd", it can send and receive data normally

**Comment by vipinpv85** [comment]
> > > > l2fwd example is worked.
> > > > ![image](https://user-images.githubusercontent.com/9845170/90612038-15350c00-e23a-11ea-9845-9341ac5867aa.png)
> > > 
> > > 
> > > this is more like #11. Hence marking this duplicate too.
> > 
> > 
> > Your dpdk debugging is incorrect, there is no X710 ports in your system. Recheck your system configuration rather than assuming the cause of errors.
> 
> ![image](https://user-images.githubusercontent.com/9845170/90629355-d14e0100-e251-11ea-8428-1aa704b1abd2.png)
> ![image](https://user-images.githubusercontent.com/9845170/90629465-02c6cc80-e252-11ea-8c09-05dd94e805b3.png)
> But I run the exmaple "l2fwd", it can send and receive data normally

your DPDK debugging is incorrect, you do not have X710 (i40e) but you have X540 (not i40e). Please cross-check before you make assumptions.

**Comment by lzskyline** [comment]
DPDK_LDFLAGS is override in configure.ac:1351, therefore "-lrte_pmd_ixgbe -Wl" is missing.
Add it and "make && make install"
problem solved.

**Comment by vipinpv85** [comment]
> DPDK_LDFLAGS is override in configure.ac:1351, therefore "-lrte_pmd_ixgbe -Wl" is missing.
> Add it and "make && make install"
> problem solved.

I humbly request to check what you are writing, as I have already communicated this 

- your error is same as https://github.com/vipinpv85/DPDK_SURICATA-4_1_1/issues/11
- your debugging of missing dpdk driver is incorrect (as you are assuming it is i40e)

**Comment by lzskyline** [comment]
> > DPDK_LDFLAGS is override in configure.ac:1351, therefore "-lrte_pmd_ixgbe -Wl" is missing.
> > Add it and "make && make install"
> > problem solved.
> 
> I humbly request to check what you are writing, as I have already communicated this
> 
> * your error is same as #11
> * your debugging of missing dpdk driver is incorrect (as you are assuming it is i40e)

you are right, but I didn't know which driver I should use, and there was no mention of how to modify makefiles in https://github.com/vipinpv85/DPDK_SURICATA-4_1_1/issues/11
just solved it and write there :P
