### ISSUE TITLE
SC_ERR_DPDK_CONFIG(319)  -  No DPDK ports found

### ISSUE THREAD

**Issue by coder-gao** [vipinpv85/DPDK_SURICATA-4_1_1#15]
hello, Vipin

Something wrong when  i run 'suricata --dpdk' : SC_ERR_DPDK_CONFIG(319)  -  No DPDK ports found
And try the command 'suricata --list-dpdkports' but  no ports display.
as follows:

![image](https://user-images.githubusercontent.com/29483273/94419658-ad1d0280-01b5-11eb-87b4-c6e5ea1c0754.png)

![image](https://user-images.githubusercontent.com/29483273/94419675-b0b08980-01b5-11eb-90c2-abf9036c1da3.png)

NIC informatinon get from './usertools/dpdk-devbind.py -s':

![image](https://user-images.githubusercontent.com/29483273/94420584-f1f56900-01b6-11eb-9809-f205d939f8ec.png)

So I want to know how to solve this problem？Thank you for your replay.

**Comment by vipinpv85** [comment]
before opening issues, please check in the issues list if similar problem has occurred before. You issue is same as  https://github.com/vipinpv85/DPDK_SURICATA-4_1_1/issues/11
