### ISSUE TITLE
NIC packet drop increase when packet rate > 2Gpps

### ISSUE THREAD

**Issue by xifeng6** [vipinpv85/DPDK_SURICATA-4_1_1#16]
Thanks for Vipin Varghese’s work.
Hardware:
Machine: Intel® Xeon® CPU Gold 5115 @ 2.40GHz
NIC: Ethernet Controller X722 for 10GbE SFP+ ( 2 * 10G), driverversion=2.4.6, firmware=3.33
SoftWare:
centos 7.8 dpdk-stable-19.11.4 DPDK_SURICATA-4_1_1 
When I was testing suricata-dpdk, the packet loss of the network card continued to increase when the packet rate was greater than 2Gpps. Use perf to observe function hotspots , ‘`common_ring_mp_enqueue`’ ‘`DpdkReleaseacket`’ ‘`ReceiveDpdkLoop`’ functions take up a large proportion rather than 50%。Can you tell me what I can do to reduce the nic packet drop.

**Comment by vipinpv85** [comment]
marking this as invalid, as same is opened in suricata discussion. I have already answered the same here [discussion](https://forum.suricata.io/t/discussion-for-dpdk-api-support-into-suricata/202/19)

**Comment by vipinpv85** [comment]
invalid, as successfully test with 4 * 10Gbps X710 on Xeon platform

![image](https://user-images.githubusercontent.com/1296097/103871821-8d21a700-50f3-11eb-89bf-2a499e8d3792.png)
