### ISSUE TITLE
I have some questions about "Work item in discussion with SURICATA team to merge" in README.md

### ISSUE THREAD

**Issue by wjf1993** [vipinpv85/DPDK_SURICATA-4_1_1#19]
You said that you didn't decide which mode to use. Have all three modes not been implemented in  DPDK_SURICATA-4_1_1?But i learn your open source and i think you has been implemented the frist mode(Primary (singleton/monolithic)).

thanks!

**Comment by vipinpv85** [comment]
thanks for your question, can you please share your reasoning or insights towards 

1. why do you think  2 other modes are not done? 
2. what are the missing pieces which make you believe so?

**Comment by wjf1993** [comment]
> thanks for your question, can you please share your reasoning or insights towards
> 
> 1. why do you think  2 other modes are not done?
> 2. what are the missing pieces which make you believe so?

**Comment by wjf1993** [comment]
> thanks for your question, can you please share your reasoning or insights towards
> 
> 1. why do you think  2 other modes are not done?
> 2. what are the missing pieces which make you believe so?

----------------------------------------------------------------
Thank you for your answer.
Bro,I'm so sorry for my incorrect question.I don't mean that you didn't implement Suricata for the other two models.Because I haven't read all your source code completely and i just read the dpdk part of your source code.So I still have a lot of details I haven't learned.
However,According to the other two models given by you,I think you will implement a separate dpdk packet sending and receiving process.But I didn't find the relevant code in the src directory. 
I'm not sure if I missed some code that led me to think that way.So I have some questions for you. Have you implemented the other two models?
thanks！

**Comment by vipinpv85** [comment]
> According to the other two models given by you,I think you will implement a separate dpdk packet sending and receiving process.But I didn't find the relevant code in the src directory.

Thank you for explaining the real question. My answer is `no I will not be giving a separate dpdk application or non-dpdk application for model-2 and model-3`. As model-2 and model-3 Suricata is a separate application and source code DPDK or non DPDK application need not be housed in suricata source code. 

> So I have some questions for you. Have you implemented the other two models?
yes implemented and tested.

**Comment by wjf1993** [comment]
> > According to the other two models given by you,I think you will implement a separate dpdk packet sending and receiving process.But I didn't find the relevant code in the src directory.
> 
> Thank you for explaining the real question. My answer is `no I will not be giving a separate dpdk application or non-dpdk application for model-2 and model-3`. As model-2 and model-3 Suricata is a separate application and source code DPDK or non DPDK application need not be housed in suricata source code.
> 
> > So I have some questions for you. Have you implemented the other two models?
> > yes implemented and tested.

-----------------------------------------------------------------------------------------------------------------------------------------

Thank you bro.I learned from your answers.I always think model-1 is the best solution for suricata.
In fact, I'm working on a project more like model 2, which is based on dpdk to implement a protocol stack to process packets and realize functions like IPS/firewall.
I will continue to learn your code and hope to contribute to your open source project in the future.
thanks！
