### ISSUE TITLE
vmware vmxnet3  [ERRCODE: SC_ERR_DPDK_CONFIG(319)] - Failed to configure port [0]

### ISSUE THREAD

**Issue by ygm521** [vipinpv85/DPDK_SURICATA-4_1_1#20]
[root@localhost bin]# ./suricata --dpdk
28/6/2021 -- 17:29:45 - <Notice> -  DPDK Mode selected
28/6/2021 -- 17:29:45 - <Notice> -  (name:suricatareassembly) 
28/6/2021 -- 17:29:45 - <Notice> -  (n:8000) 
28/6/2021 -- 17:29:45 - <Notice> - This is Suricata version 4.1.4 RELEASE
28/6/2021 -- 17:29:46 - <Warning> - [ERRCODE: SC_ERR_NO_RULES(42)] - No rule files match the pattern /usr/local/var/lib/suricata/rules/suricata.rules
28/6/2021 -- 17:29:46 - <Warning> - [ERRCODE: SC_ERR_NO_RULES_LOADED(43)] - 1 rule files specified, but no rule was loaded at all!
28/6/2021 -- 17:29:46 - <Notice> -  Port 0 RX-q (4) hence trying RSS
Ethdev port_id=0 requested Rx offloads 0xe doesn't match Rx offloads capabilities 0x82a1d in rte_eth_dev_configure()
28/6/2021 -- 17:29:46 - <Error> - [ERRCODE: SC_ERR_DPDK_CONFIG(319)] - Failed to configure port [0]
28/6/2021 -- 17:29:46 - <Error> - [ERRCODE: SC_ERR_DPDK_CONFIG(319)] -  Failed to setup Ports!
28/6/2021 -- 17:29:46 - <Error> - [ERRCODE: SC_ERR_DPDK_CONFIG(319)] -  Failed to set config!

**Comment by vipinpv85** [comment]
this is a very straightforward issue from PMD in use (vmxnet3). Humble request to explore and read about vmxnet capability from 

- [http://doc.dpdk.org/guides/nics/overview.html](url) generic overview of NIC
- [http://doc.dpdk.org/guides/nics/vmxnet3.html](url) to identify the supported Offload.

**Comment by ygm521** [comment]
What is the reason? Does it not support vmxnet3 and e1000 network cards? Or is it the cause of the configuration error?I think the point is that it is not available on the vmware virtual machine

**Comment by vipinpv85** [comment]
@ygm521 I do not follow you new question `what is the reason? Does it not support vmxnet3 and e1000 network cards? Or is it the cause of the configuration error?`  becasue

- based **on screenshot with no description**, I have shared you have to do for `vmxnet3`
- pointed 2 URL which helps you to understand.

For your second question `I think the point is that it is not available on the vmware virtual machine`, my answer is `you are free to assume and think what you like. I can not change what you think`.  

Note: there are many who ran this in HOST and GUEST OS (with vmxnet3 and e1000)

**Comment by vipinpv85** [comment]
Hope you have gone the DPDK documentation links to understand the vmxnet3 issue. If not here is my summary as per the documentation from DPDK 21.05

1. RSS supported in DPDK 21.05 - yes
2. RSS supported with VLAN offload - no
3. RX offload shared for port 0 is `0xe`
4. As per DPDK 21.05 code base ` #define DEV_RX_OFFLOAD_VLAN_STRIP  0x00000001`

Hence RSS config fails.

Possible fix
1. Edit yaml number of ports to 1 9to disable RSS0 and check if it works.
2. If step 1 succeeds, edit `src/runmode-dpdk.c` RSS to reflect only `IP, TCP and UDP`

**Comment by ygm521** [comment]
@vipinpv85 Thank you, thank you, I'm already running it on vmware of centos 7 system。

**Comment by vipinpv85** [comment]
ahh ok, good to hear now it is working, were you able to run with RSS?

**Comment by ygm521** [comment]
not use rss

**Comment by ZhangYiXi-dev** [comment]
hello，how to not use rss，i just let queues=1 in yaml,but it can't works
Ethdev port_id=0 invalid rss_hf: 0x3bffc, valid value: 0x0
12/6/2022 -- 15:49:52 - <Error> - [ERRCODE: SC_ERR_DPDK_CONFIG(319)] - Failed to configure port [0]
12/6/2022 -- 15:49:52 - <Error> - [ERRCODE: SC_ERR_DPDK_CONFIG(319)] -  Failed to setup Ports!
12/6/2022 -- 15:49:52 - <Error> - [ERRCODE: SC_ERR_DPDK_CONFIG(319)] -  Failed to set config!

**Comment by vipinpv85** [comment]
if one sets queues to 1, RSS is disabled. SO in the YAML file my expectation is

```
 # port config
  port-config-0: [mempool=portpool,queues=1,rss-tuple=3,ebpf=NULL,jumbo=no,mtu=1500]
  port-config-1: [mempool=portpool,queues=1,rss-tuple=3,ebpf=NULL,jumbo=no,mtu=1500]
  port-config-2: [mempool=portpool,queues=1,rss-tuple=3,ebpf=NULL,jumbo=no,mtu=1500]
  port-config-3: [mempool=portpool,queues=1,rss-tuple=3,ebpf=NULL,jumbo=no,mtu=1500]
```

Hence without the right configuration you can not expect the right result.
