### ISSUE TITLE
Can describe as IDS or IPS,how to build the network topology?

### ISSUE THREAD

**Issue by ygm521** [vipinpv85/DPDK_SURICATA-4_1_1#21]
Can describe as IDS or IPS, in the two scenarios, how to build the network topology? Can you give me an example? Thanks a lot.
This may help more people understand how to use ids and ips. It is best to solve the network problem with a computer

**Comment by vipinpv85** [comment]
all the details are present in readme, wiki and yaml dpdk section. this is same as suricata model of using IDS and IPS. this is not a bug.

If your intention is update readme, you can raise a feature request.
