### ISSUE TITLE
[ERRCODE: SC_ERR_DPDK_CONFIG(319)] -  Failed to setup Ports!

### ISSUE THREAD

**Issue by skshtshw** [vipinpv85/DPDK_SURICATA-4_1_1#24]
suricata --dpdk

20/3/2022 -- 19:20:18 - <Notice> -  addr_dst_match4_cnt 1 addr_src_match4_cnt 1 addr_dst_match6_cnt i1 addr_src_match6_cnt 1
20/3/2022 -- 19:20:18 - <Notice> -  IPV4
20/3/2022 -- 19:20:18 - <Notice> -  0:ffffffff
20/3/2022 -- 19:20:18 - <Notice> -  0:ffffffff
20/3/2022 -- 19:20:18 - <Notice> - -----------------------
20/3/2022 -- 19:20:18 - <Notice> -  IPV6
20/3/2022 -- 19:20:18 - <Notice> -  0-0-0-0:ffffffff-ffffffff-ffffffff-ffffffff
20/3/2022 -- 19:20:18 - <Notice> -  0-0-0-0:ffffffff-ffffffff-ffffffff-ffffffff
20/3/2022 -- 19:20:18 - <Notice> - -----------------------
20/3/2022 -- 19:20:18 - <Notice> -  Source Port
20/3/2022 -- 19:20:18 - <Notice> -  port:port2 (0:ffff)
20/3/2022 -- 19:20:18 - <Notice> -  Destiantion Port
20/3/2022 -- 19:20:18 - <Notice> -  port:port2 (0:ffff)
20/3/2022 -- 19:20:18 - <Notice> -  prio 3
20/3/2022 -- 19:20:18 - <Notice> -  Port 0 RX-q (4) hence trying RSS
20/3/2022 -- 19:20:18 - <Error> - [ERRCODE: SC_ERR_DPDK_CONFIG(319)] -  Failed to setup Ports!
20/3/2022 -- 19:20:18 - <Error> - [ERRCODE: SC_ERR_DPDK_CONFIG(319)] -  Failed to set config!

DPDK:
![image](https://user-images.githubusercontent.com/5217896/159198393-620b5199-7590-4982-9885-a3e48dbbaec6.png)
./build/app/testpmd -l 0-1 -n 2 -- -i
EAL: Detected 2 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: PCI device 0000:02:01.0 on NUMA socket -1
EAL:   probe driver: 8086:100f net_e1000_em
EAL: PCI device 0000:02:05.0 on NUMA socket -1
EAL:   probe driver: 8086:100f net_e1000_em
EAL: PCI device 0000:03:00.0 on NUMA socket -1
EAL:   probe driver: 8086:10d3 net_e1000_em
Interactive-mode selected
testpmd: create a new mbuf pool <mbuf_pool_socket_0>: n=155456, size=2176, socket=0
testpmd: preferred mempool ops selected: ring_mp_mc
Configuring Port 0 (socket 0)
Port 0: 00:0C:29:CE:9F:CF
Configuring Port 1 (socket 0)
Port 1: 00:0C:29:CE:9F:D9
Checking link statuses...

dpdk-stable-19.11.11 and Suricata version 4.1.4 RELEASE;

So I want to know how to solve this problem？Thank you for your replay.

**Comment by vipinpv85** [comment]
thanks for your query. please find my answers below

- this is not a bug or issue
- based on testpmd logs, ooks liek you are running in avm with e1000 nic or running.
- current PMD build and tested with are `-Wl,-lrte_pmd_af_packet -Wl,-lrte_pmd_i40e -Wl,-lrte_pmd_memif -Wl,-lrte_pmd_null -Wl,-lpcap -Wl,-lrte_pmd_ring -Wl,-lrte_pmd_tap -Wl,-lrte_pmd_virtio -Wl,-lrte_bus_vmbus`

Hence if you want to add support for your desired PMD please edit `configure.ac` and rebuilt.
