### ISSUE TITLE
vmware centos7   e1000 Failed to configure port [0]

### ISSUE THREAD

**Issue by ZhangYiXi-dev** [vipinpv85/DPDK_SURICATA-4_1_1#25]
hello,firstly,i have added -Wl,-lrte_pmd_e1000 in configure.ac , and i set queues=1 in yaml(because e1000 can't support rss),then i run it,it will "Ethdev port_id=0 nb_tx_queues=2 > 1" , so i set txq_count=1 , then :Ethdev port_id=0 invalid rss_hf: 0x3bffc, valid value: 0x0
![image](https://user-images.githubusercontent.com/83794882/173223902-fb312efd-0ac4-4a21-ab7f-4c03736d1719.png)

and l2fwd can work normally
![image](https://user-images.githubusercontent.com/83794882/173223865-38d3ccb9-0c7e-462b-96ac-ca72aac6d66d.png)

i didn't know why caused it? can you help me? thank you !

**Comment by ZhangYiXi-dev** [comment]
i have solved it,the e1000 can't support rss,so delete the code of rss,and let rss_hf=0

**Comment by vipinpv85** [comment]
> hello,firstly,i have added -Wl,-lrte_pmd_e1000 in configure.ac , and i set queues=1 in yaml(because e1000 can't support rss),then i run it,it will "Ethdev port_id=0 nb_tx_queues=2 > 1" , so i set txq_count=1 , then :Ethdev port_id=0 invalid rss_hf: 0x3bffc, valid value: 0x0 ![image](https://user-images.githubusercontent.com/83794882/173223902-fb312efd-0ac4-4a21-ab7f-4c03736d1719.png)
> 
> and l2fwd can work normally ![image](https://user-images.githubusercontent.com/83794882/173223865-38d3ccb9-0c7e-462b-96ac-ca72aac6d66d.png)
> 
> i didn't know why caused it? can you help me? thank you !

But confused with the request as the code already takes care of this

```
	dpdk_ports[i].rxq_count = (dpdk_ports[i].rxq_count == 0) ? 1 : dpdk_ports[i].rxq_count;
	dpdk_ports[i].txq_count = (dpdk_ports[i].txq_count == 0) ? 1 : dpdk_ports[i].txq_count;

		if (dpdk_ports[i].rxq_count == 1) {
			local_port_conf.rxmode.mq_mode = ETH_MQ_RX_NONE;
		} else {
			SCLogNotice(" Port %u RX-q (%u) hence trying RSS", i, dpdk_ports[i].rxq_count);

			local_port_conf.rx_adv_conf.rss_conf.rss_hf &= dev_info.flow_type_rss_offloads;
			if (local_port_conf.rx_adv_conf.rss_conf.rss_hf != port_conf.rx_adv_conf.rss_conf.rss_hf) {
				SCLogInfo(" Port %u modified RSS hash function based on hardware support,"
						"requested:%"PRIx64" configured:%"PRIx64,
						i,
						port_conf.rx_adv_conf.rss_conf.rss_hf,
						local_port_conf.rx_adv_conf.rss_conf.rss_hf);

				if (local_port_conf.rx_adv_conf.rss_conf.rss_hf == 0)
					return -EINVAL;
			}
		}

```

**Comment by vipinpv85** [comment]
> i have solved it,the e1000 can't support rss,so delete the code of rss,and let rss_hf=0

without analyzing I can not reply. But since the work around worked for you I am ignoring.

**Comment by ZhangYiXi-dev** [comment]
thank you for your response! the process of slove my problem is:
firstly the error is  : Ethdev port_id=0 nb_tx_queues=2 > 1,so i let txq_count=1 or 0

then,the error is Ethdev port_id=0 invalid rss_hf: 0x3bffc, valid value: 0x0 , i think because can't supports rss ,so i delete the picture below:
![image](https://user-images.githubusercontent.com/83794882/173571530-df139d15-34fc-4663-8e0c-4ffb1cb28a58.png)

and then error is "Failed to rte_eth_dev_rss_hash_conf_get for", i don't know why cause this ,i have set queues=1 in yaml ,
by rights rss should not be involved,so i delete the code below:
![image](https://user-images.githubusercontent.com/83794882/173572341-273ab73e-2287-4ddd-beb3-8cb3e4491416.png)

finally,the code can run

**Comment by ZhangYiXi-dev** [comment]
> > hello,firstly,i have added -Wl,-lrte_pmd_e1000 in configure.ac , and i set queues=1 in yaml(because e1000 can't support rss),then i run it,it will "Ethdev port_id=0 nb_tx_queues=2 > 1" , so i set txq_count=1 , then :Ethdev port_id=0 invalid rss_hf: 0x3bffc, valid value: 0x0 ![image](https://user-images.githubusercontent.com/83794882/173223902-fb312efd-0ac4-4a21-ab7f-4c03736d1719.png)
> > and l2fwd can work normally ![image](https://user-images.githubusercontent.com/83794882/173223865-38d3ccb9-0c7e-462b-96ac-ca72aac6d66d.png)
> > i didn't know why caused it? can you help me? thank you !
> 
> But confused with the request as the code already takes care of this
> 
> ```
> 	dpdk_ports[i].rxq_count = (dpdk_ports[i].rxq_count == 0) ? 1 : dpdk_ports[i].rxq_count;
> 	dpdk_ports[i].txq_count = (dpdk_ports[i].txq_count == 0) ? 1 : dpdk_ports[i].txq_count;
> 
> 		if (dpdk_ports[i].rxq_count == 1) {
> 			local_port_conf.rxmode.mq_mode = ETH_MQ_RX_NONE;
> 		} else {
> 			SCLogNotice(" Port %u RX-q (%u) hence trying RSS", i, dpdk_ports[i].rxq_count);
> 
> 			local_port_conf.rx_adv_conf.rss_conf.rss_hf &= dev_info.flow_type_rss_offloads;
> 			if (local_port_conf.rx_adv_conf.rss_conf.rss_hf != port_conf.rx_adv_conf.rss_conf.rss_hf) {
> 				SCLogInfo(" Port %u modified RSS hash function based on hardware support,"
> 						"requested:%"PRIx64" configured:%"PRIx64,
> 						i,
> 						port_conf.rx_adv_conf.rss_conf.rss_hf,
> 						local_port_conf.rx_adv_conf.rss_conf.rss_hf);
> 
> 				if (local_port_conf.rx_adv_conf.rss_conf.rss_hf == 0)
> 					return -EINVAL;
> 			}
> 		}
> ```

thank you for your response! the process of slove my problem is:
firstly the error is : Ethdev port_id=0 nb_tx_queues=2 > 1,so i let txq_count=1 or 0

then,the error is Ethdev port_id=0 invalid rss_hf: 0x3bffc, valid value: 0x0 , i think because can't supports rss ,so i delete the picture below:
![image](https://user-images.githubusercontent.com/83794882/173573132-bbd482a4-bbb6-4a79-9bf6-ce8093598a50.png)

and then error is "Failed to rte_eth_dev_rss_hash_conf_get for", i don't know why cause this ,i have set queues=1 in yaml ,
by rights rss should not be involved,so i delete the code below:
![image](https://user-images.githubusercontent.com/83794882/173573235-d62bb509-b234-4b64-b134-240043f07b0c.png)

finally,the code can run

**Comment by vipinpv85** [comment]
> > > hello,firstly,i have added -Wl,-lrte_pmd_e1000 in configure.ac , and i set queues=1 in yaml(because e1000 can't support rss),then i run it,it will "Ethdev port_id=0 nb_tx_queues=2 > 1" , so i set txq_count=1 , then :Ethdev port_id=0 invalid rss_hf: 0x3bffc, valid value: 0x0 ![image](https://user-images.githubusercontent.com/83794882/173223902-fb312efd-0ac4-4a21-ab7f-4c03736d1719.png)
> > > and l2fwd can work normally ![image](https://user-images.githubusercontent.com/83794882/173223865-38d3ccb9-0c7e-462b-96ac-ca72aac6d66d.png)
> > > i didn't know why caused it? can you help me? thank you !
> > 
> > 
> > But confused with the request as the code already takes care of this
> > ```
> > 	dpdk_ports[i].rxq_count = (dpdk_ports[i].rxq_count == 0) ? 1 : dpdk_ports[i].rxq_count;
> > 	dpdk_ports[i].txq_count = (dpdk_ports[i].txq_count == 0) ? 1 : dpdk_ports[i].txq_count;
> > 
> > 		if (dpdk_ports[i].rxq_count == 1) {
> > 			local_port_conf.rxmode.mq_mode = ETH_MQ_RX_NONE;
> > 		} else {
> > 			SCLogNotice(" Port %u RX-q (%u) hence trying RSS", i, dpdk_ports[i].rxq_count);
> > 
> > 			local_port_conf.rx_adv_conf.rss_conf.rss_hf &= dev_info.flow_type_rss_offloads;
> > 			if (local_port_conf.rx_adv_conf.rss_conf.rss_hf != port_conf.rx_adv_conf.rss_conf.rss_hf) {
> > 				SCLogInfo(" Port %u modified RSS hash function based on hardware support,"
> > 						"requested:%"PRIx64" configured:%"PRIx64,
> > 						i,
> > 						port_conf.rx_adv_conf.rss_conf.rss_hf,
> > 						local_port_conf.rx_adv_conf.rss_conf.rss_hf);
> > 
> > 				if (local_port_conf.rx_adv_conf.rss_conf.rss_hf == 0)
> > 					return -EINVAL;
> > 			}
> > 		}
> > ```
> 
> thank you for your response! the process of slove my problem is: firstly the error is : Ethdev port_id=0 nb_tx_queues=2 > 1,so i let txq_count=1 or 0
> 
> then,the error is Ethdev port_id=0 invalid rss_hf: 0x3bffc, valid value: 0x0 , i think because can't supports rss ,so i delete the picture below: ![image](https://user-images.githubusercontent.com/83794882/173573132-bbd482a4-bbb6-4a79-9bf6-ce8093598a50.png)
> 
> and then error is "Failed to rte_eth_dev_rss_hash_conf_get for", i don't know why cause this ,i have set queues=1 in yaml , by rights rss should not be involved,so i delete the code below: ![image](https://user-images.githubusercontent.com/83794882/173573235-d62bb509-b234-4b64-b134-240043f07b0c.png)
> 
> finally,the code can run

Couple of things to consider

1. RSS is for RX queue
2. The code checks for rx queue count==1 and disable RSS 

hence to disable RSS for your use case with has 1 RXQ it will work.

I do not understand what you are explaining with respect to TXQ.
