### ISSUE TITLE
runmode-dpdk.h:60:19: error: ‘RTE_MAX_ETHPORTS’ undeclared here (not in a function)

### ISSUE THREAD

**Issue by tolunFdancer** [vipinpv85/DPDK_SURICATA-4_1_1#3]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vipinpv85** [comment]
please run 'grep -nr dpdk config.log' in you folder.

note: I am not sure why are sending me 

```
Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Describe the solution you'd like
A clear and concise description of what you want to happen.

Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've considered.

Additional context
Add any other context or screenshots about the feature request here.
```

**Comment by tolunFdancer** [comment]
Thanks! I just want to konw if you had already face the question.  
Now I meet this error when I run "make -j 10" :   DPDK_SURICATA-4_1_1-master/suricata-4.1.4/src/suricata.c:912: undefined reference to `TmModuleReceiveDpdkRegister'.
If you could help me ,thank you very much!

**Comment by vipinpv85** [comment]
project 4.1.4 is work in progress, hence you will be seeing build issues.

In my local branch, I have fixed these and have a functional working model (no data processing yet).

**Comment by tolunFdancer** [comment]
So when can you commit this fix?

**Comment by vipinpv85** [comment]
In my spare time. Surprised with your request since I have already mentioned 4.1.1 is work in progress. While 3.0 is fully functional

**Comment by tolunFdancer** [comment]
Thanks ! Sorry for waste your time.

**Comment by vipinpv85** [comment]
The files are added, hence you would face the issue. It is not about wasting time. If you want a working prototype use 3.0.

**Comment by vipinpv85** [comment]
Files are uploaded. If you want a working prototype please try 3.0

**Comment by tolunFdancer** [comment]
Thanks. When I run "make -j 10" whit 3.0, it turns out "app-layer-smtp.c:388:17: error: ‘for’ loop initial declarations are only allowed in C99 mode" . I tryed with "CFLAGS=-std=gnu99 make -j 10", still do not work. Can you give me some advices, Thanks a lot!

**Comment by vipinpv85** [comment]
https://stackoverflow.com/questions/29338206/error-for-loop-initial-declarations-are-only-allowed-in-c99-mode

or 
update g++

**Comment by vipinpv85** [comment]
if there are no updates, I assume this was some environment or gcc issue.
