### ISSUE TITLE
When the DPDK_suricata4.1.1 could instead of DPDK_suricata3.0?

### ISSUE THREAD

**Issue by tolunFdancer** [vipinpv85/DPDK_SURICATA-4_1_1#4]
Hi，I wanna konw when the DPDK_suricata4.1.1 could work. Now I run DPDK_suricata3.0 successful, I want to updata DPDK_suricata3.0 to DPDK_suricata4.1.1.

**Comment by vipinpv85** [comment]
Hi @tolunFdancer, thanks for the question. I try to work on the same in my spare time. I would like to complete basic functions with offload within 2 months.

Please feel free to contribute too.

**Comment by vipinpv85** [comment]
@tolunFdancer are you helping us to work of any items? Please do update your plans so I can work as updated ASAP.

**Comment by vipinpv85** [comment]
basic DPDK Suricata with 4.1.4 is up and runing
