### ISSUE TITLE
Package not logged to fast.log

### ISSUE THREAD

**Issue by FLY199806** [vipinpv85/DPDK_SURICATA-4_1_1#8]
Hi
The Title is my ploblem.Here are some details.
I installed and tested the program on a six port physical machine. The first four network ports are bound with dpdk. I bind the image port on a switch to the first network port of dpdk, and then run the program in the way of readme. However, there is no log output to fast.log. So I bound the image port to another normal network port that is not bound to dpdk, and he will output the log to fast.log normally.

Thanks
Chen

Maybe useful:
[EAL]
-c 1
--log-level=eal,1
--file-prefix=suricata_1
-m=128
-w=0000:01:00.0
#-w=05:00.0

[PORT-0]
rx-queues=2
tx-queues=2
# 0, 3, 5, tep
rss-tuple=3
jumbo=no
mtu=1500
core=0

#[PORT-1]
#rx-queues=2
#tx-queues=2
# 0, 3, 5, tep
#rss-tuple=3
#jumbo=no
#mtu=1500
#core=0

**Comment by vipinpv85** [comment]
> The Title is my ploblem. Here are some details.

[Answer] I am assuming the title is `Package not logged to fast.log` and not project title `DPDK_SURICATA-4_1_1`. I am not interested in changing the project title, hence will not be entertaining the same.

>I installed and tested the program on a six-port physical machine. The first four network ports are bound with dpdk.

[Answer] My current implementation is not intended to run both DPDK and non DPDK port. 

If this is a requirement, please use template for a feature and add a request and not as issue.

> I bind the image port on a switch to the first network port of dpdk, and then run the program in the way of the readme. However, there is no log output to fast.log

[Answer] please refer `https://github.com/vipinpv85/DPDK_SURICATA-4_1_1/issues/4` this is work in progress and not complete. Currently, RX thread is able to grab packets but does not share for decode threads in this repository.

> So I bound the image port to another normal network port that is not bound to dpdk, and he will output the log to fast.log

[Answer] expected as explained above.

hence I am marking this as `invalid` and making the request to open `feature reqest` if the intention is run DPDK and non DPDK ports together.
